# Generated by Django 4.1.3 on 2022-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('roll', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
